"""Isolation Enforcement Policy.

v3.1 Fix: Enforces isolation requirements based on trust and risk level.
Implements 4-level Execution Trust Model per Synapse Architecture Spec:
  - Trusted: Built-in skills, full access within capability tokens
  - Verified: Passed testing + AST analysis, isolated process
  - Unverified: Just generated by LLM, strict sandbox only
  - Human-approved: Approved by user, isolated process with extended capabilities
"""
from enum import Enum

PROTOCOL_VERSION: str = "1.0"
SPEC_VERSION: str = "3.1"


class RuntimeIsolationType(str, Enum):
    """Runtime isolation types ordered by strictness."""
    NONE = "none"
    SUBPROCESS = "subprocess"
    CONTAINER = "container"
    SANDBOX = "sandbox"


class SkillTrustLevel(str, Enum):
    """4-level Execution Trust Model per Synapse Architecture Spec.

    | Level          | Source                              | Isolation            |
    |----------------|-------------------------------------|----------------------|
    | TRUSTED        | Built-in skills shipped with core   | Main process         |
    | VERIFIED       | Passed auto-tests + AST analysis    | Isolated process     |
    | UNVERIFIED     | Just generated by LLM               | Strict sandbox       |
    | HUMAN_APPROVED | Approved by user after code review  | Isolated + extended  |
    """
    TRUSTED = "trusted"
    VERIFIED = "verified"
    UNVERIFIED = "unverified"
    HUMAN_APPROVED = "human_approved"


class IsolationEnforcementPolicy:
    """Enforces isolation requirements for skill execution.

    Rules (v3.1 + Execution Trust Model):
    - UNVERIFIED → SANDBOX mandatory (no system calls, no network)
    - VERIFIED → SUBPROCESS with declared capability limits
    - HUMAN_APPROVED → SUBPROCESS with extended capability request
    - TRUSTED → SUBPROCESS (main process for low risk)
    - risk_level >= 3 → CONTAINER minimum regardless of trust
    - risk_level >= 5 → requires human approval (handled by ExecutionGuard)
    """

    protocol_version: str = "1.0"

    def __init__(self):
        self.protocol_version = "1.0"

    def get_required_isolation(
        self,
        trust_level: str,
        risk_level: int
    ) -> RuntimeIsolationType:
        """Get required isolation type for trust/risk level.

        Args:
            trust_level: Trust level (trusted, verified, unverified, human_approved)
            risk_level: Risk level 1-5

        Returns:
            Required RuntimeIsolationType
        """
        # Rule: risk_level >= 3 always requires container minimum
        if risk_level >= 3:
            return RuntimeIsolationType.CONTAINER

        # Rule: unverified always requires strict sandbox
        if trust_level == SkillTrustLevel.UNVERIFIED or trust_level == "unverified":
            return RuntimeIsolationType.SANDBOX

        # Rule: verified runs in isolated subprocess
        if trust_level == SkillTrustLevel.VERIFIED or trust_level == "verified":
            return RuntimeIsolationType.SUBPROCESS

        # Rule: human_approved runs in isolated subprocess (can request extended caps)
        if trust_level == SkillTrustLevel.HUMAN_APPROVED or trust_level == "human_approved":
            return RuntimeIsolationType.SUBPROCESS

        # Rule: trusted with low risk can use subprocess
        if trust_level == SkillTrustLevel.TRUSTED or trust_level == "trusted":
            if risk_level <= 1:
                return RuntimeIsolationType.SUBPROCESS
            return RuntimeIsolationType.SUBPROCESS

        # Default to container for safety (unknown trust level)
        return RuntimeIsolationType.CONTAINER
