"""Developer Agent — autonomous skill code generation.

Protocol Version: 1.0
Specification: 3.1

Implements the full CreateSkill pipeline:
  1. Receive task description from Critic/Orchestrator
  2. Build structured LLM prompt with BaseSkill interface
  3. Call LLM → parse Python class from response
  4. AST security scan (block dangerous patterns)
  5. Generate unit tests
  6. Return GeneratedSkill ready for SkillRegistry

On every step an audit event is emitted.
"""
import ast
import hashlib
import logging
import re
import textwrap
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from synapse.observability.logger import audit

PROTOCOL_VERSION: str = "1.0"
SPEC_VERSION: str = "3.1"
logger = logging.getLogger(__name__)

# Dangerous AST node types / names that must be blocked
BLOCKED_BUILTINS = {
    "eval", "exec", "compile", "__import__", "breakpoint",
    "open",        # allowed only via fs-capability, not raw
    "input",
}
BLOCKED_MODULES = {
    "os", "sys", "subprocess", "shutil", "socket",
    "ctypes", "pickle", "marshal", "shelve",
    "importlib", "builtins", "__builtins__",
}


def _safe_exec(code_obj, namespace: dict) -> None:
    """Execute compiled skill code in an isolated namespace.

    This function exists to provide a single, audited point where dynamic
    code execution happens. Called ONLY after AST security scan passes.

    Bandit B102 is suppressed here: exec() is intentional, controlled,
    and runs in an isolated namespace dict per SYSTEM_SPEC_v3.1 §4.
    """
    exec(code_obj, namespace)  # nosec B102


@dataclass
class GeneratedSkill:
    """A skill produced by DeveloperAgent — not yet active."""
    skill_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    version: str = "1.0.0"
    description: str = ""
    code: str = ""
    tests: str = ""
    required_capabilities: List[str] = field(default_factory=list)
    risk_level: int = 2
    security_issues: List[str] = field(default_factory=list)
    passed_ast_scan: bool = False
    protocol_version: str = PROTOCOL_VERSION

    def to_dict(self) -> Dict[str, Any]:
        return {
            "skill_id": self.skill_id,
            "name": self.name,
            "version": self.version,
            "description": self.description,
            "code_length": len(self.code),
            "tests_length": len(self.tests),
            "required_capabilities": self.required_capabilities,
            "risk_level": self.risk_level,
            "security_issues": self.security_issues,
            "passed_ast_scan": self.passed_ast_scan,
            "protocol_version": self.protocol_version,
        }


SKILL_TEMPLATE = '''"""Auto-generated skill: {name}

Description: {description}
Generated by: DeveloperAgent
Protocol Version: 1.0
"""
from typing import Any, Dict, Optional
from synapse.skills.base import BaseSkill
from synapse.observability.logger import audit

PROTOCOL_VERSION: str = "1.0"


class {class_name}(BaseSkill):
    """Skill: {description}"""

    async def execute(self, context: Any = None, **kwargs) -> Dict[str, Any]:
        """Execute the skill.

        Args:
            context: ExecutionContext with agent_id, trace_id, capabilities
            **kwargs: Skill-specific parameters

        Returns:
            Dict with 'result', 'status', 'protocol_version'
        """
        audit(
            event="skill_execute_start",
            skill="{name}",
            protocol_version=PROTOCOL_VERSION,
        )

        try:
{implementation}
            return {{
                "status": "completed",
                "result": result,
                "protocol_version": PROTOCOL_VERSION,
            }}

        except Exception as e:
            audit(event="skill_execute_error", skill="{name}", error=str(e))
            return {{
                "status": "error",
                "error": str(e),
                "protocol_version": PROTOCOL_VERSION,
            }}
'''

TEST_TEMPLATE = '''"""Unit tests for {name} skill."""
import pytest
from unittest.mock import AsyncMock, MagicMock


class Test{class_name}:
    """Tests for {name} skill."""

    @pytest.fixture
    def skill(self):
        from {module_path} import {class_name}
        return {class_name}()

    @pytest.fixture
    def context(self):
        ctx = MagicMock()
        ctx.agent_id = "test_agent"
        ctx.trace_id = "trace_001"
        ctx.capabilities = []
        return ctx

    @pytest.mark.asyncio
    async def test_execute_returns_result(self, skill, context):
        result = await skill.execute(context=context)
        assert isinstance(result, dict)
        assert "status" in result
        assert result.get("protocol_version") == "1.0"

    @pytest.mark.asyncio
    async def test_execute_completed_status(self, skill, context):
        result = await skill.execute(context=context)
        assert result["status"] in ("completed", "error")

    def test_protocol_version(self, skill):
        assert skill.protocol_version == "1.0"
'''


class DeveloperAgent:
    """Agent that generates fully working skill code via LLM.

    Pipeline:
    1. Build structured prompt from task description
    2. Call LLM → extract Python class
    3. AST security scan
    4. Generate unit tests
    5. Return GeneratedSkill
    """

    protocol_version: str = PROTOCOL_VERSION

    def __init__(
        self,
        llm_provider: Any = None,
        skill_registry: Any = None,
        policy_engine: Any = None,
    ):
        self.llm_provider = llm_provider
        self.skill_registry = skill_registry
        self.policy_engine = policy_engine
        audit(
            event="developer_agent_initialized",
            has_llm=llm_provider is not None,
            protocol_version=self.protocol_version,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def generate_skill(
        self,
        task_description: str,
        seed: Optional[int] = None,
    ) -> Dict[str, Any]:
        """Full CreateSkill pipeline.

        Returns a dict with 'skill' (GeneratedSkill) and 'status'.
        """
        audit(
            event="skill_generation_started",
            task=task_description[:120],
            seed=seed,
            protocol_version=self.protocol_version,
        )

        skill_name = self._task_to_skill_name(task_description)
        class_name = self._to_class_name(skill_name)
        description = task_description[:200]

        # Step 1 — generate implementation via LLM (or template fallback)
        implementation = await self._generate_implementation(
            task_description, skill_name, class_name
        )

        # Step 2 — assemble full skill code
        code = SKILL_TEMPLATE.format(
            name=skill_name,
            class_name=class_name,
            description=description,
            implementation=textwrap.indent(implementation, "            "),
        )

        # Step 3 — AST security scan
        issues = self._ast_security_scan(code)
        passed_scan = len(issues) == 0

        # Step 4 — determine capabilities and risk from implementation text
        caps = self._infer_capabilities(implementation + task_description)
        risk = self._infer_risk(caps)

        # Step 5 — generate unit tests
        module_path = f"skills.dynamic.{skill_name}"
        tests = TEST_TEMPLATE.format(
            name=skill_name,
            class_name=class_name,
            module_path=module_path,
        )

        skill = GeneratedSkill(
            name=skill_name,
            version="1.0.0",
            description=description,
            code=code,
            tests=tests,
            required_capabilities=caps,
            risk_level=risk,
            security_issues=issues,
            passed_ast_scan=passed_scan,
        )

        audit(
            event="skill_generation_completed",
            skill_id=skill.skill_id,
            name=skill_name,
            passed_ast_scan=passed_scan,
            issues_count=len(issues),
            risk_level=risk,
            protocol_version=self.protocol_version,
        )

        return {
            "skill": skill,
            "status": "ready_for_review" if passed_scan else "security_issues",
            "protocol_version": PROTOCOL_VERSION,
        }

    async def register_skill(self, skill: GeneratedSkill) -> Dict[str, Any]:
        """Register an approved GeneratedSkill in the SkillRegistry."""
        if not self.skill_registry:
            return {"status": "error", "error": "No skill registry configured"}
        if not skill.passed_ast_scan:
            return {"status": "error", "error": "Skill failed AST security scan"}

        try:
            from synapse.core.models import SkillManifest, ResourceLimits
            from synapse.core.isolation_policy import RuntimeIsolationType

            manifest = SkillManifest(
                name=skill.name,
                version=skill.version,
                description=skill.description,
                capabilities_required=skill.required_capabilities,
                isolation_type=RuntimeIsolationType.SUBPROCESS,
                resource_limits=ResourceLimits(),
                protocol_version=PROTOCOL_VERSION,
            )

            # Create handler from generated code
            handler = self._build_handler(skill)

            await self.skill_registry.register(
                skill_id=skill.skill_id,
                manifest=manifest,
                handler=handler,
            )

            audit(
                event="skill_registered",
                skill_id=skill.skill_id,
                name=skill.name,
                protocol_version=self.protocol_version,
            )

            return {"status": "registered", "skill_id": skill.skill_id, "protocol_version": PROTOCOL_VERSION}

        except Exception as e:
            audit(event="skill_registration_failed", error=str(e), protocol_version=self.protocol_version)
            return {"status": "error", "error": str(e), "protocol_version": PROTOCOL_VERSION}

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    async def _generate_implementation(
        self, task: str, name: str, class_name: str
    ) -> str:
        """Generate the body of execute() via LLM or structured fallback."""
        if self.llm_provider:
            prompt = self._build_prompt(task, name, class_name)
            try:
                response = await self.llm_provider.generate(prompt)
                content = response.get("content", "")
                extracted = self._extract_python_body(content)
                if extracted:
                    return extracted
            except Exception as e:
                logger.warning("LLM generation failed: %s", e)

        # Structured fallback based on task keywords
        return self._template_implementation(task, name)

    def _build_prompt(self, task: str, name: str, class_name: str) -> str:
        return f"""You are an expert Python developer creating a skill for an autonomous agent platform.

TASK: {task}

Generate ONLY the body of the `execute()` method for a Python class called `{class_name}`.
The method signature is:
    async def execute(self, context=None, **kwargs) -> dict:

Requirements:
- Store your final answer in a variable called `result`
- Handle exceptions with try/except
- Do NOT import os, sys, subprocess, socket, or other dangerous modules
- Use only: pathlib.Path, json, re, datetime, typing, asyncio
- The last line before the return must set `result`
- Return only the method body code (no class definition, no def line)

RESPOND WITH ONLY PYTHON CODE, no markdown, no explanations."""

    def _extract_python_body(self, llm_output: str) -> str:
        """Extract clean Python method body from LLM response."""
        # Strip markdown code blocks
        code = re.sub(r"```python\s*", "", llm_output)
        code = re.sub(r"```\s*", "", code)
        code = code.strip()
        # Remove leading def/async def lines if LLM included them
        lines = code.split("\n")
        filtered = []
        skip_def = False
        for line in lines:
            stripped = line.strip()
            if stripped.startswith("async def execute") or stripped.startswith("def execute"):
                skip_def = True
                continue
            if skip_def and stripped.startswith('"""'):
                # Skip docstring
                continue
            skip_def = False
            filtered.append(line)
        result = "\n".join(filtered).strip()
        # Validate it parses
        try:
            ast.parse(f"async def _f():\n{textwrap.indent(result, '    ')}")
            return result
        except SyntaxError:
            return ""

    def _template_implementation(self, task: str, name: str) -> str:
        """Generate a working template implementation based on task keywords."""
        task_lower = task.lower()
        # File operations
        if any(k in task_lower for k in ["read file", "open file", "load file"]):
            return (
                'path = kwargs.get("path", ".")\n'
                'from pathlib import Path\n'
                'content = Path(path).read_text(encoding="utf-8")\n'
                'result = {"path": path, "content": content, "size": len(content)}'
            )
        if any(k in task_lower for k in ["write file", "save file", "create file"]):
            return (
                'path = kwargs.get("path", "output.txt")\n'
                'content = kwargs.get("content", "")\n'
                'from pathlib import Path\n'
                'Path(path).write_text(content, encoding="utf-8")\n'
                'result = {"path": path, "bytes_written": len(content)}'
            )
        # HTTP request
        if any(k in task_lower for k in ["http", "fetch", "request", "api", "url", "web"]):
            return (
                'import httpx, asyncio\n'
                'url = kwargs.get("url", "https://httpbin.org/get")\n'
                'async with httpx.AsyncClient(timeout=10) as client:\n'
                '    resp = await client.get(url)\n'
                'result = {"url": url, "status_code": resp.status_code, "content": resp.text[:2000]}'
            )
        # JSON processing
        if any(k in task_lower for k in ["json", "parse", "convert"]):
            return (
                'import json\n'
                'data = kwargs.get("data", "{}")\n'
                'parsed = json.loads(data) if isinstance(data, str) else data\n'
                'result = {"parsed": parsed, "keys": list(parsed.keys()) if isinstance(parsed, dict) else []}'
            )
        # Search / text analysis
        if any(k in task_lower for k in ["search", "find", "analyze", "text"]):
            return (
                'import re\n'
                'text = kwargs.get("text", "")\n'
                'pattern = kwargs.get("pattern", r"\\w+")\n'
                'matches = re.findall(pattern, text)\n'
                'result = {"matches": matches[:100], "count": len(matches)}'
            )
        # Generic fallback
        return (
            f'# Auto-generated handler for: {task[:60]}\n'
            'params = {k: v for k, v in kwargs.items()}\n'
            'result = {\n'
            '    "task": "' + name + '",\n'
            '    "params_received": list(params.keys()),\n'
            '    "message": "Task handler ready — implement specific logic here",\n'
            '}'
        )

    def _ast_security_scan(self, code: str) -> List[str]:
        """AST-based security scan. Returns list of issues (empty = safe)."""
        issues = []
        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            return [f"SyntaxError: {e}"]

        for node in ast.walk(tree):
            # Check imports
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                module = ""
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        module = alias.name.split(".")[0]
                        if module in BLOCKED_MODULES:
                            issues.append(f"Blocked import: {alias.name}")
                else:
                    module = (node.module or "").split(".")[0]
                    if module in BLOCKED_MODULES:
                        issues.append(f"Blocked import from: {node.module}")
            # Check dangerous function calls
            elif isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name):
                    if node.func.id in BLOCKED_BUILTINS:
                        issues.append(f"Blocked builtin: {node.func.id}()")
                elif isinstance(node.func, ast.Attribute):
                    full = f"{getattr(node.func.value, 'id', '?')}.{node.func.attr}"
                    if any(blocked in full for blocked in ["os.system", "os.popen", "subprocess.Popen",
                                                            "subprocess.run", "subprocess.call"]):
                        issues.append(f"Blocked call: {full}()")

        return issues

    def _infer_capabilities(self, text: str) -> List[str]:
        """Infer required capabilities from task description."""
        caps = []
        t = text.lower()
        if any(k in t for k in ["read file", "open file", "load"]):
            caps.append("fs:read")
        if any(k in t for k in ["write file", "save", "create file"]):
            caps.append("fs:write")
        if any(k in t for k in ["http", "request", "fetch", "api", "url", "web"]):
            caps.append("net:http")
        if any(k in t for k in ["process", "subprocess", "run command"]):
            caps.append("os:process")
        if any(k in t for k in ["memory", "store", "recall"]):
            caps.append("memory:write")
        if not caps:
            caps.append("memory:read")  # default minimal cap
        return caps

    def _infer_risk(self, caps: List[str]) -> int:
        """Infer risk level 1-5 from capability list."""
        risk_map = {
            "fs:delete": 4, "fs:execute": 5, "os:process": 4,
            "net:scan": 4, "sys:shutdown": 5, "code:execute": 5,
            "fs:write": 2, "net:http": 2, "fs:read": 1,
            "memory:write": 2, "memory:read": 1,
        }
        return max((risk_map.get(c, 1) for c in caps), default=1)

    def _task_to_skill_name(self, task: str) -> str:
        """Convert task description to snake_case skill name."""
        clean = re.sub(r"[^a-zA-Z0-9 ]", "", task)
        words = clean.lower().split()[:4]
        return "_".join(words) or "generated_skill"

    def _to_class_name(self, snake_name: str) -> str:
        """Convert snake_case to PascalCase."""
        return "".join(w.capitalize() for w in snake_name.split("_")) + "Skill"

    def _build_handler(self, skill: GeneratedSkill):
        """Compile generated code and return execute() coroutine.

        Security: exec() is intentionally used here to dynamically load
        LLM-generated skills that have ALREADY passed AST security scanning
        (see _ast_security_scan). The code runs in an isolated namespace
        with no access to the outer scope. This is the sandboxed execution
        layer documented in SYSTEM_SPEC_v3.1 §4 (Execution Trust Model).
        """
        if not skill.passed_ast_scan:
            logger.warning("Refusing to build handler for skill that failed AST scan: %s", skill.name)
            async def blocked_handler(**kwargs):
                return {"status": "blocked", "error": "Skill failed security scan"}
            return blocked_handler

        namespace: Dict[str, Any] = {}
        try:
            # Skills reach this point ONLY after:
            # 1. AST security scan passes (no os/sys/subprocess/eval/exec imports)
            # 2. Human approval (in production flow)
            # The isolated namespace prevents access to outer scope.
            compiled = compile(skill.code, f"<synapse_skill:{skill.name}>", "exec")
            _safe_exec(compiled, namespace)
            class_name = self._to_class_name(skill.name)
            cls = namespace.get(class_name)
            if cls:
                instance = cls()
                return instance.execute
        except Exception as e:
            logger.warning("Could not compile skill %s: %s", skill.name, e)

        async def noop_handler(**kwargs):
            return {"status": "not_compiled", "error": "Skill code compilation failed"}

        return noop_handler

    def create_prompt(self, task_description: str, seed: Optional[int] = None) -> str:
        name = self._task_to_skill_name(task_description)
        class_name = self._to_class_name(name)
        return self._build_prompt(task_description, name, class_name)
